name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      COMMIT_SHA: ${{ github.sha }}
      DEPLOY: ${{ secrets.DEPLOY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          # Install dependencies from all requirements.txt files
          find . -name requirements.txt | while read req; do
            echo "Installing from $req"
            pip install -r "$req"
          done

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('frontend/package-lock.json', 'frontend/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # Authenticate to Google Cloud only when deployment is enabled
      - name: Google Auth (SA Key)
        if: env.DEPLOY == 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud SDK
        if: env.DEPLOY == 'true'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for gcr.io
        if: env.DEPLOY == 'true'
        run: gcloud auth configure-docker gcr.io -q

      - name: Build Docker images (tag with SHA)
        run: |
          services=(
            ingestion/coinbase
            ingestion/coingecko
            ingestion/polygon
            ingestion/coinapi
            ingestion/yfinance
            features
            signals
            paper_trading
            prompt_engine
          )
          for service in "${services[@]}"; do
            image=gcr.io/${PROJECT_ID}/${service//\//-}:${COMMIT_SHA}
            echo "Building $image from $service..."
            docker build -t "$image" "$service"
            if [ "${DEPLOY}" = "true" ]; then
              echo "Pushing $image..."
              docker push "$image"
            fi
          done

      - name: Deploy to Cloud Run
        if: env.DEPLOY == 'true'
        run: |
          services=(
            ingestion/coinbase
            ingestion/coingecko
            ingestion/polygon
            ingestion/coinapi
            ingestion/yfinance
            features
            signals
            paper_trading
            prompt_engine
          )
          # Service account with BigQuery and Secret Manager access
          SERVICE_ACCOUNT="github-deployer@${PROJECT_ID}.iam.gserviceaccount.com"
          
          for service in "${services[@]}"; do
            image=gcr.io/${PROJECT_ID}/${service//\//-}:${COMMIT_SHA}
            service_name=${service//\//-}
            echo "Deploying $service_name to Cloud Run in ${REGION}..."
            gcloud run deploy "$service_name" \
              --image "$image" \
              --region "$REGION" \
              --platform managed \
              --allow-unauthenticated \
              --service-account "$SERVICE_ACCOUNT" \
              --port 8000 \
              --set-env-vars "GCP_PROJECT_ID=${PROJECT_ID}" \
              --max-instances 10 \
              --memory 512Mi \
              --cpu 1 \
              --timeout 300
          done